<a href="https://colab.research.google.com/github/Enzomania/Pytorch-Tutorial/blob/main/tensor_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [8]:
my_torch2 = torch.arange(10)
my_torch2[1] = 1234
my_torch2

tensor([   0, 1234,    2,    3,    4,    5,    6,    7,    8,    9])

In [9]:
my_torch3 = my_torch2.reshape(2,-1)
my_torch3

tensor([[   0, 1234,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [10]:
## reshape und view sind referenzbasiert
my_torch2[1] = 5432
my_torch3

tensor([[   0, 5432,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [11]:
my_torch4 = my_torch3.reshape(-1,2)
my_torch4

tensor([[   0, 5432],
        [   2,    3],
        [   4,    5],
        [   6,    7],
        [   8,    9]])

In [12]:
## slice
my_torch5 = my_torch4[:,1]
my_torch5

tensor([5432,    3,    5,    7,    9])

In [13]:
my_torch6 = my_torch4[:,1:]
my_torch6

tensor([[5432],
        [   3],
        [   5],
        [   7],
        [   9]])