<a href="https://colab.research.google.com/github/Enzomania/Pytorch-Tutorial/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

# LISTS

In [ ]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

# NUMPY ARRAYS

In [ ]:
np1 = np.random.rand(3,4)
np1

array([[0.50521666, 0.16958431, 0.9396868 , 0.35029661],
       [0.04643666, 0.310625  , 0.89304837, 0.16833457],
       [0.79765159, 0.71998108, 0.98199134, 0.03481545]])

# TENSORS

In [ ]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.7534,  0.7262,  0.4758, -1.4886],
        [ 0.1888, -0.0233,  0.7674,  0.4998],
        [ 0.0879,  0.4610,  0.8382,  0.8363]])

In [ ]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.5052, 0.1696, 0.9397, 0.3503],
        [0.0464, 0.3106, 0.8930, 0.1683],
        [0.7977, 0.7200, 0.9820, 0.0348]], dtype=torch.float64)